# Generated by Django 5.2.5 on 2025-08-28 07:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_careerapplication_cover_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyinfo',
            name='why_hands_nepal',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
