# Generated by Django 5.1.1 on 2025-08-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_governance'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='past_or_present',
            field=models.CharField(choices=[('past', 'Past Client'), ('present', 'Present Client')], default='present', max_length=20, verbose_name='Client Type'),
        ),
    ]
